### ISSUE TITLE
Update login form fields for enhanced UX and security

### ISSUE THREAD

**Issue by conor-jh** [team-skechers/Lunchin#13]
### User story
As an end-user, I should be able to log in with a conventional login form so that I can trust the app I’m using is legitimate, secure, and user-friendly.

### Tasks
- [x] Update existing `div` element to an HTML `form`
- [x] Add proper `type` attributes to login input fields
- [x] Use form’s native `action` and `method` attributes to simplify XHR request for authentication (#26)
- [x] Style login form so it’s “branded” and pretty ✨ (#14)
