### ISSUE TITLE
Fetch Yelp data with GraphQL

### ISSUE THREAD

**Issue by conor-jh** [team-skechers/Lunchin#17]
### User story
As a developer, I should be able to fetch data from Yelp’s API using GraphQL, so that we minimize extraneous HTTP requests and our end-users enjoy performance enhancements.

### Tasks
- [x] Define GraphQL schema required for client-side data (#18)
- [x] Integrate into Yelp controller (without regressions 🤙)
- [x] Verify `response` to client contains properly-formatted JSON response object
