### ISSUE TITLE
Style restaurant data for easier scanning

### ISSUE THREAD

**Issue by conor-jh** [team-skechers/Lunchin#23]
### User story
As a user, I should be able to scan restaurant cards to quickly review information I care about, so that I don’t have to spend mental energy distinguishing restaurant data.

### Tasks
- [ ] Reinforce data hierarchy by minimizing labels 
- [ ] Introduce iconography, color, etc. to add visual anchors to unique data types
- [ ] Leverage component props to dynamically display (and style) restaurant data
- [ ] Display map for visualizing location (#22)
- [ ] Display open/closed indicator (#24)
