### ISSUE TITLE
Provide user feedback on login form

### ISSUE THREAD

**Issue by conor-jh** [team-skechers/Lunchin#27]
### User story
As an end user, I should be able to see if my login credentials are invalid (whether unauthenticated or invalid input) so that my login failed in some way.

### Tasks 
- [ ] Add event handler for invalid input
- [ ] Update state in main app upon unsuccessful login attempt
- [ ] Implement invalid input styles as shown below

<img width="429" alt="Screen Shot 2019-05-22 at 11 37 37 AM" src="https://user-images.githubusercontent.com/31315610/58188128-1289e680-7c86-11e9-8859-278446e24051.png">

**Comment by conor-jh** [comment]
### Style notes
#### Invalid field values
Border color: `#C34A43`
#### Message values
Color: `#C34A43`
Font stack: `'Avenir Next', 'Avenir', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;`
Font size: `0.875em`
