### ISSUE TITLE
Secure Yelp API key

### ISSUE THREAD

**Issue by conor-jh** [team-skechers/Lunchin#9]
### User story
As a developer, I should be able to rely on my Node environment for our app’s Yelp API key so that I trust our connection remains secure.

### Tasks

- [x] Generate new API key from Yelp
- [x] Remove old API key from public repo
- [x] Instruct team to setup `.env` config files

**Comment by Donaldblanc** [comment]
completed
